sonar.projectKey=sonarqube-test-coverage-project
sonar.projectName=SonarQube Test Coverage Project
sonar.sourceEncoding=UTF-8

# Paths
sonar.sources=src
sonar.tests=tests
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Exclusions
sonar.exclusions=**/*.d.ts,node_modules/**
sonar.test.exclusions=node_modules/**

# Code coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Duplication
sonar.cpd.exclusions=**/*test.ts,**/*.test.ts
